## You should change each of the following fields
## to customize your blog

title: Data Grill Blog
description: "Grill the Numbers, Savor the Insights" 
author: Brayden Humpherys
author_description: "As a curious student of statistics, I believe there are hidden stories in data all across the world. As I enter the world of statistics and data science, I hope to
 use data to find the right recipe for success. No matter the industry, there is data that needs to be understood and 'grilled'. Join me as I explore and share the 'flavors' of data science in simple and 'normal' talk!" 

url: https://BraydenHumpherys.github.io ## change this to https://yourusername.github.io
baseurl: /Data-Grill-Blog ## change this to the name of your blog repository
header_image: /data-grill.png.PNG ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  BraydenHumpherys
    twitter: 
    facebook: 
    email: 21brayden.rich@gmail.com
    linkedin: brayden-humpherys
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




